### PR TITLE
Build python package in test and not rely on C compiler

### PR DESCRIPTION
**Pull request by timj**

### CODE REVIEW

**Comment by timj** [comment]
Why is the gcc version so old on travis trusty? Maybe we should switch the rebuild test to something trivial like `rebuild python` since the point is to test that `rebuild` works with the install, not that the compiler is new.

**Comment by jhoblitt** [comment]
Note that trusty was tried in #144 and didn't work.  The trusty image has likely been updated since then, so probably worth trying.

**Comment by timj** [comment]
trust is still using ancient gcc 4.8.4.

**Comment by jhoblitt** [comment]
I think the build probably be changed to use `docker.io/lsstsqre/centos:7-stackbase`

**Comment by timj** [comment]
For some reason the travis job failed because it was trying the previous commit not the current HEAD.

**Comment by timj** [comment]
@jhoblitt what do you think? This shows it was an issue with the compiling and still tests that `rebuild` is working properly.

**Comment by timj** [comment]
@jhoblitt I'll remove the trusty change before merging.

**Comment by jhoblitt** [comment]
This seems reasonable but I still feel the ultimate fix is to test inside our own docker image.

**Pull request merged**
