### PR TITLE
Add obs_subaru to repos.yaml.

### PR DESCRIPTION
**Pull request by timj**

### CODE REVIEW

**Comment by timj** [comment]
@jdswinbank the policy for lsstsw changes to `repos.yaml` is that a PR is requested, the changes are checked by Travis and then the committer can self merge the PR without asking permission if the checks pass.

**Comment by jdswinbank** [comment]
Thanks @timj!

Can you point me at where that policy is defined, please? https://confluence.lsstcorp.org/display/LDMDG/Adding+a+new+package+to+the+build doesn't mention it.

**Comment by timj** [comment]
I can't remember. @jhoblitt ?

**Comment by ktlim** [comment]
It's RFC-75, which ends with a request from me to Josh to add this to the above page.  This is now DM-4318.

**Comment by jdswinbank** [comment]
Thanks @ktlim!

**Pull request merged**
