### PR TITLE
DM-6058: Add numexpr and bottleneck to package list

### PR DESCRIPTION
**Pull request by danielsf**
Add numexpr and bottlenecks to the list of conda packages automatically installed by lsstsw.

Also: add the pandas EUPS stub to repos.yaml

### CODE REVIEW

**Comment by jhoblitt** [comment]
@timj I am OK with this PR but rather it isn't merged until my question on https://github.com/lsst/pandas/pull/1 is answered.

**Comment by timj** [comment]
@danielsf I think you are missing the patch to the deploy script to add `numexpr` etc to the list for the bleeding edge install.

**Comment by danielsf** [comment]
@timj is that not controlled by `conda_packages-[linux, osx]-64.txt`?  Which piece of code do I need to patch (I'm only vaguely aware of how lsstsw works)

**Comment by timj** [comment]
Those text files are for pinning the versions. When we want to float up to the most recent versions for testing we bypass those and specify floating versions of all packages. See the `PACKAGES` variable in `bin/deploy` (search for `pandas`).

**Pull request merged**
