### PR TITLE
fix missing conda package versions

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
@timj travis is running very slow this morning.  py3 on OSX still hasn't run yet but it appears the package changes were linux only.

**Comment by jhoblitt** [comment]
I'm gong to merge this and then rebase #157 .

**Comment by danielsf** [comment]
Sorry.  I just cargo-culted my changes on #156.  What has proven to be unreliable and what needs additional fixing?

**Comment by timj** [comment]
You will need to rebase because @jhoblitt changed the files you changed.

**Comment by danielsf** [comment]
Oh.  Okay.  *That* I understand.

**Pull request merged**
