### PR TITLE
Add mariadb to repos.yaml.

### PR DESCRIPTION
**Pull request by fjammes**

### CODE REVIEW

**Comment by fjammes** [comment]
Please run next command on lsst-de to install MariaDB dependencies:
yum install -y cmake zlib-devel xz-devel ncurses-devel

**Comment by jhoblitt** [comment]
@fjammes all of those packages are part of the system packages set except for `xz-devel`.  I'm going to merge this PR but we may need pass an RFC to add that as a system dep.

**Comment by fjammes** [comment]
Hi Josh,

Thanks for merging this PR. Do you know the RFC process please?
xz-devel is mandatory for mariadb build.

Regards

**Comment by jmatt** [comment]
Hi Fabrice,

The RFC docs can be found here:

https://confluence.lsstcorp.org/display/LDMDG/Adding+a+new+package+to+the+build

Just ask if you have further questions.

**Pull request merged**
